### ISSUE TITLE
bug: problems at fleek init

### ISSUE THREAD

**Issue by fguisso** [ublue-os/fleek#323]
**Describe the bug**
??

**To Reproduce**
- Install nix `sh <(curl -L https://nixos.org/nix/install) --daemon`
- Open a new terminal
- Init Fleet `nix run "https://getfleek.dev/latest.tar.gz" -- init`

**Expected behavior**
Init with no problems.

**Environment**
 - OS: Proxmox container lxc Debian 12 (2gb / 2vcpu / 10gb disk)
 - Shell: bash
 - fleek version: latest

**Additional context**
```bash
$ nix run "https://getfleek.dev/latest.tar.gz" -- init
panic: runtime error: slice bounds out of range [:2] with length 1

goroutine 1 [running]:
github.com/ublue-os/fleek.locale(...)
        github.com/ublue-os/fleek/fleek.go:48
github.com/ublue-os/fleek.NewApp()
        github.com/ublue-os/fleek/fleek.go:19 +0x1cf
github.com/ublue-os/fleek/internal/fleekcli.init.0()
        github.com/ublue-os/fleek/internal/fleekcli/main.go:39 +0x17
```

**Comment by tomaszn** [comment]
Same here. Ubuntu 23.10.
